pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'Java 21'
    }

    stages {
        stage('Build') {
            steps {
                dir('starter_code') {
                    sh 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('starter_code') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    dir('starter_code') {
                        junit 'target/surefire-reports/*.xml'
                        jacoco execPattern: 'target/jacoco.exec'
                    }
                }
            }
        }

        stage('Package') {
            steps {
                dir('starter_code') {
                    sh 'mvn package'
                }
            }
        }

        stage('Archive') {
            steps {
                dir('starter_code') {
                    archiveArtifacts artifacts: 'target/*.war', fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
